### ISSUE TITLE
Add project to awesome lists

### ISSUE THREAD

**Issue by skatkov** [skatkov/jekyll-news-sitemap#4]
Add this project to these lists:
https://github.com/planetjekyll/awesome-jekyll-plugins
https://github.com/planetjekyll/awesome-jekyll

**Comment by KirillSokur** [comment]
Added to both lists. 
Waiting for approval.
![image](https://user-images.githubusercontent.com/13163708/78803858-b341db80-79e9-11ea-9a58-2069c1e4047c.png)


***

![image](https://user-images.githubusercontent.com/13163708/78803944-c94f9c00-79e9-11ea-9f23-ca6f31507f72.png)

**Comment by KirillSokur** [comment]
- Both approved

![image](https://user-images.githubusercontent.com/13163708/78814039-379b5b00-79f8-11ea-9b4b-c82ae90aa64a.png)

***

![image](https://user-images.githubusercontent.com/13163708/78814121-5a2d7400-79f8-11ea-99f4-a95b126e0a6a.png)

**Comment by skatkov** [comment]
Thanks!
